name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      
      - name: Install VSCode extension dependencies
        run: |
          if [ -d "vscode-extension" ]; then
            cd vscode-extension
            npm install
          fi
      
      - name: Run tests
        run: |
          if [ -f "./run-tests.sh" ]; then
            chmod +x ./run-tests.sh
            ./run-tests.sh
          else
            echo "No test script found, running basic tests"
            pytest
          fi
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-reports/
